version: "3.9"

services:

    auth-service:
        build: 
            context: ./auth
        container_name: "auth-service"
        ports: 
            - "4001:4001"
        volumes:
            - /media/sf_backend/auth:/home/app
            - /home/app/node_modules
            - node_modulesSv:/home/app/node_modules

    product-service:
        build: 
            context: ./products
        container_name: "product-service"
        ports: 
            - "4002:4002"
        volumes:
            - /media/sf_backend/products:/home/app
            - /home/app/node_modules

    router: 
        image: nginx
        ports: 
            - 8000:80
        volumes:
            - ./sharedAuthService.conf:/etc/nginx/sharedAuthService.conf
            - ./sharedProductService.conf:/etc/nginx/sharedProductService.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - auth-service

volumes:
    node_modulesSv:
    

